name: Labeler
on:
  pull_request_target:
    types:
      - opened
      - edited
      - ready_for_review
      - synchronize
  issue_comment:
    types: [created, edited]
jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install yq

      - name: Get Reviewers
        id: reviewers
        run: echo ::set-output name=reviewers::$(cat ./OWNERS | yq .reviewers -M | grep , | sed 's/[",]//g')

      - name: Get Approvers
        id: approvers
        run: echo ::set-output name=approvers::$(cat ./OWNERS | yq .approvers -M | grep , | sed 's/[",]//g')

      - name: Add Size label
        if: github.event_name == 'pull_request_target'
        uses: "pascalgn/size-label-action@v0.4.3"
        env:
          GITHUB_TOKEN: "${{ secrets.BOT_PAT }}"

      - name: Add WIP label / comment trigger
        if: |
          contains(github.event.pull_request.title, 'wip') ||
          (contains(github.event.comment.html_url, '/pull/') && 
          contains(github.event.comment.body, '/wip'))
        uses: andymckay/labeler@master
        with:
          repo-token: ${{ secrets.BOT_PAT }}
          add-labels: 'WIP'

      - name: Remove WIP label
        if: |
          contains(github.event.comment.html_url, '/pull/') && 
          contains(github.event.comment.body, '/wip cancel')
        uses: andymckay/labeler@master
        with:
          repo-token: ${{ secrets.BOT_PAT }}
          remove-labels: 'WIP'

      - name: Add bug label / comment trigger
        if: |
          contains(github.event.pull_request.title, 'bug') ||
          (contains(github.event.comment.html_url, '/pull/') && 
          contains(github.event.comment.body, '/bug'))
        uses: andymckay/labeler@master
        with:
          repo-token: ${{ secrets.BOT_PAT }}
          add-labels: 'bug'

      - name: Remove bug label
        if: |
          contains(github.event.comment.html_url, '/pull/') && 
          contains(github.event.comment.body, '/bug cancel')
        uses: andymckay/labeler@master
        with:
          repo-token: ${{ secrets.BOT_PAT }}
          remove-labels: 'bug'

      - name: Add Approved label
        if: |
          contains(github.event.comment.html_url, '/pull/') &&
          (contains(github.event.comment.body, '/approve') || contains(github.event.comment.body, '/approve')) &&
          contains(steps.approvers.outputs.approvers, github.event.comment.user.login || 'null')
        uses: andymckay/labeler@master
        with:
          repo-token: ${{ secrets.BOT_PAT }}
          add-labels: 'approved', 'lgtm'

      - name: Remove Approved label
        if: |
          contains(github.event.comment.html_url, '/pull/') &&
          (contains(github.event.comment.body, '/approve') || contains(github.event.comment.body, '/approve cancel')) &&
          contains(steps.approvers.outputs.approvers, github.event.comment.user.login || 'null')
        uses: andymckay/labeler@master
        with:
          repo-token: ${{ secrets.BOT_PAT }}
          remove-labels: 'approved'

      - name: Add LGTM label
        if: |
          contains(github.event.comment.html_url, '/pull/') && 
          contains(github.event.comment.body, '/lgtm') &&
          contains(steps.approvers.outputs.reviewers, github.event.comment.user.login || 'null') &&
          github.event.issue.user.login != github.event.comment.user.login
        uses: andymckay/labeler@master
        with:
          repo-token: ${{ secrets.BOT_PAT }}
          add-labels: 'lgtm'
          remove-labels: 'WIP'

      - name: Remove LGTM label
        if: |
          contains(github.event.comment.html_url, '/pull/') && 
          contains(github.event.comment.body, '/lgtm cancel') &&
          contains(steps.approvers.outputs.reviewers, github.event.comment.user.login || 'null') &&
          github.event.issue.user.login != github.event.comment.user.login
        uses: andymckay/labeler@master
        with:
          repo-token: ${{ secrets.BOT_PAT }}
          remove-labels: 'lgtm'

      - name: Remove LGTM Label if new push is made
        if: |
         github.event_name == 'pull_request_target' && github.event.action == 'synchronize' &&
         contains(github.event.pull_request.labels.*.name, 'lgtm')
        uses: andymckay/labeler@master
        with:
          repo-token: ${{ secrets.BOT_PAT }}
          remove-labels: 'lgtm'

      - name: Add Hold label
        if: |
          contains(github.event.comment.html_url, '/pull/') && 
          contains(github.event.comment.body, '/hold') &&
          contains(steps.approvers.outputs.approvers, github.event.comment.user.login || 'null')
        uses: andymckay/labeler@master
        with:
          repo-token: ${{ secrets.BOT_PAT }}
          add-labels: 'hold'

      - name: Remove Hold label
        if: |
          contains(github.event.comment.html_url, '/pull/') && 
          contains(github.event.comment.body, '/hold cancel') &&
          contains(steps.approvers.outputs.approvers, github.event.comment.user.login || 'null')
        uses: andymckay/labeler@master
        with:
          repo-token: ${{ secrets.BOT_PAT }}
          remove-labels: 'hold'

