name: React-Styleguide
on:
  push:
    branches:
      - main
  pull_request_target:
    types:
      - opened
      - synchronize
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        env:
          CONTEXT: ${{ toJSON(github) }}
        run: echo "$CONTEXT"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
      - run: yarn styleguide:build

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        env:
          BRANCH: "${{ github.event_name == 'pull_request_target' && github.head_ref || 'main' }}"
        with:
          token: ${{ secrets.BOT_PAT }}
          branch: ${{ env.BRANCH }} # The branch the action should deploy to.
          folder: doc # The folder that the styleguide:build script generates files.
          clean: true # Automatically remove deleted files from the deploy branch
          target-folder: doc # The folder that we serve our React-Styleguide files from
